***Write a function so that the columns of the output matrix are powers of the input vector.***

In [1]:
import numpy as np

In [2]:
def alex_vander_matrix(uniarray,n,increasing=False):
    if not increasing:
        print(np.array([x**(n-1-i) for x in uniarray for i in range(n)]).reshape(len(uniarray),n))
    else:
        print(np.array([x**i for x in uniarray for i in range(n)]).reshape(len(uniarray),n))
        
in_array = [1,2,3,4,5]
no_col=5
print('Input array is:',np.array(in_array),'\n')
print('Number of columns:',no_col,'\n')
print('Vander matrix in decreasing order:')
alex_vander_matrix(in_array,no_col)
print('\n Vander matrix in increasing order:')
alex_vander_matrix(in_array,no_col,increasing=True)


Input array is: [1 2 3 4 5] 

Number of columns: 5 

Vander matrix in decreasing order:
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]

 Vander matrix in increasing order:
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


***Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.***

In [3]:
input_array = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window=3
output = []
n=len(input_array)
def moving_avg():
    for i in range(0,n):
        if i<n-window+1:
            output.append((input_array[i]+input_array[i+1]+input_array[i+2])/window)
        else:
            break
    print(output)        

In [4]:
moving_avg()

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]


In [5]:
for i in range(len(output)):
    print(f'y{i+1} ={round(output[i],2)}')

y1 =5.0
y2 =4.67
y3 =5.67
y4 =6.67
y5 =9.67
y6 =28.67
y7 =49.33
y8 =72.67
y9 =84.0
y10 =93.33
y11 =116.33
